### ISSUE TITLE
How to use it offline

### ISSUE THREAD

**Issue by Shekharrajak** [SciRuby/nyaplot#5]
Hello,

I see there is 3 JS files need to be loaded into iruby notebook to display the charts. They are : 

    d3:'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min',
    downloadable: 'http://cdn.rawgit.com/domitry/d3-downloadable/master/d3-downloadable'
    nyaplot : 'https://github.com/domitry/Nyaplotjs/blob/v2/release/nyaplot.js'

So I tried to load these files in iruby notebook, but I didn't see charts when my internet is off. Is that means these JS files have some internal things that works through internet ?

**Comment by v0dro** [comment]
Yes. These JS files are downloaded from the internet each time you run a nyaplot script. Which is why I asked you to not repeat this flaw in daru-view.
